Handle field removal with changelog
opticdev/optic pull request #1070
Opened 2021-07-30 15:21 UTC by niclim

## Why
Describe the motivation for the changes.

I initially tried splitting up the shape projection into an internal projection and a spectacle projection, however I think this made the code more complex, and it's really only to power the changelog for removal (which we might want to think more carefully about how we power this). 

As a result, I'm going to treat `removed` fields by marking them as `isRemoved` and filtering out values conditionally based on whether we want to query removed fields.

## What
What's changing? Anything of note to call out?

- Changed `without_field` to change the field to `is_removed` to true
- Filtered out is_removed field nodes s it's treated effectively the same way as orphaning the child
- Added in RemovedIn edges for the changelog history for removed fields.

TODO
- [ ] Add a test for removed nodes and the shape projection with the return and is_removed fields
- [ ] Test whether the internal projection and spectacle choice map returns this correctly

## Validation
* [ ] CI passes
* [ ] Verified in staging
* etc...

2021-07-30 15:22 UTC, niclim commented on workspaces/optic-engine/src/queries/spectacle/spec_choices.rs
> +          let object_fields = queries.resolve_shape_field_id_and_names(&choice.shape_id, true);
In the external / spectacle projection / shapeViewerProjection - we want to include removed nodes, so we can display the data associated with the removed field. (TODO test this out)

2021-07-30 15:23 UTC, niclim commented on workspaces/optic-engine/src/shapes/traverser.rs
> +                .resolve_shape_field_id_and_names(&choice.shape_id, false);
In the internal projection, we do _not_ want to resolve removed nodes, the only thing we need the removed nodes for is display / information in the changelog, not for modifying fields

2021-07-30 17:58 UTC, niclim commented on workspaces/optic-engine/src/queries/snapshots/optic_engine__queries__shape__test__can_generate_remove_field_commands__choice_mapping.snap
> +                ],
This is the most important snapshot to review - the others just add `is_removed` to the all the keys. We expect removed nodes to be displayed in the spectacle shapeViewerProjection, however they have the key `is_removed` which can then be appropriately removed from the FE (similar to how endpoints, requests and responses are handled)

2021-07-30 18:08 UTC, niclim commented on workspaces/optic-engine/src/shapes/traverser.rs
> +                .resolve_shape_fields_nodes(&choice.shape_id, false);
In this case, traversing the shape for generating a diff should _not_ query removed shapes

2021-08-02 09:09 UTC, JaapRood requested changes
My initial thought was: fair enough, lets do what's pragmatic and enhance from there. However, changing the handling of removing field in this way, by not actually removing the node from the node_id's Map and not removing the edge, is not an acceptable solution. It goes against why this projection is modelled as a graph and the queries we have built, are building and will build on top of it.

I'm still happy for a pragmatic solution where we don't actually have to fork these projections, or happy to take on a more formal split between the two projections, but either way this approach is taking on a technical debt that's not worth it.

2021-08-02 09:09 UTC, JaapRood commented on workspaces/optic-engine/src/projections/shape.rs
> -    // eventual garbage collection.
I don't think we can get away with this. In a graph representation, the entire point is that you can construct queries by walking it, and rely on edges being representative. Adding the "is removed" filter to a couple accessor methods is really brittle, as often the graph is walked directly (as it is with the new edit shape stuff).

2021-08-03 13:54 UTC, closed without merging