Blog: How to discuss api changes during code review
opticdev/optic pull request #851
Opened 2021-06-03 11:09 UTC by ukmadlz

## Why
New blog post: How to discuss API changes during code review

2021-06-03 16:29 UTC, acunniffe approved these changes

2021-06-03 17:27 UTC, devdoshi commented on website/blog/how-to-discuss-api-changes-during-code-review.md
> +These open comments are also a great place to have discussions with your team, tag users who need to know about the changes, and suggest updates.
per https://github.com/opticdev/optic-changelog readme:
I think it's also worth calling out this option to help rope in the right people
```
SUBSCRIBERS (optional) - comma-separated value of GitHub usernames to include in the PR comment, which will notify the users of an API change
```

2021-06-03 17:28 UTC, devdoshi commented
nice!

2021-06-03 17:37 UTC, LouManglass requested changes
Optic 9 images are all correct, I'd like to get these updated to Optic 10 though to provide a consistent experience.

2021-06-03 17:38 UTC, devdoshi commented
> Optic 9 images are all correct, I'd like to get these updated to Optic 10 though to provide a consistent experience.

good call @LouManglass I set a mental note to look at the images in the PR but then they weren't in the PR so I didn't look at them :(

2021-06-03 17:52 UTC, LouManglass commented
> > Optic 9 images are all correct, I'd like to get these updated to Optic 10 though to provide a consistent experience.
> 
> good call @LouManglass I set a mental note to look at the images in the PR but then they weren't in the PR so I didn't look at them :(

To be fair, I "cheated" and pushed it to staging. I usually either run it locally or on staging to read it as it's rendered so I get the full experience.

2021-06-10 13:20 UTC, LouManglass requested changes
@ukmadlz 
The instructions have been updated appropriately, but the UI images are still from Optic 9. (Note: the final image of the article from the changelog/GitHub Actions result, after "You can dive in deeper by clicking “Review” to see exactly which API requests were affected.", is correct) 

Examples:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/241059/121531801-c1fc9780-c9cc-11eb-8a81-771bac331985.png">

<img width="752" alt="image" src="https://user-images.githubusercontent.com/241059/121531873-d04ab380-c9cc-11eb-8fc5-bca754f3cb5e.png">

<img width="752" alt="image" src="https://user-images.githubusercontent.com/241059/121531936-e0fb2980-c9cc-11eb-9281-eff06016e443.png">

2021-06-10 17:38 UTC, LouManglass commented
> I only asked for the install instructions to be updated, to publish today I don't think I can go back to the author.

Cool, I'll fix these after some meetings today and get it deployed before the day's over. It looks pretty straightforward and includes all the necessary information to reproduce, shouldn't take long.

2021-06-10 21:37 UTC, LouManglass approved these changes

2021-06-11 16:12 UTC, merged